# Site settings
title: I ðŸ’– Ruby
title_html:
  big: I <img src="/assets/images/site-heart.webp" height="26" width="26" /> Ruby	
  small: I <img src="/assets/images/site-heart.webp" height="16" width="16" /> Ruby	
site_heart:
  big: <img src="/assets/images/site-heart.webp" height="26" width="26" />
  small: <img src="/assets/images/site-heart.webp" height="16" width="16" />
email: josh@trueheart78.com
emoji:
  src: "/assets/images"

description: "The website of one trueheart78"

baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://www.trueheart78.com" # the base hostname & protocol for your site
domain: "www.trueheart78.com"

github_username: "trueheart78"
twitter_username: "trueheart78"

# Build settings
markdown: kramdown
kramdown:
    input: GFM

# Gems - supported https://pages.github.com/versions/
plugins:
  - jemoji
